from cli.config.config import (
    APP_TITLE,
    CATEGORY_LIST,
    DEFAULT_ENTRY_ICON_PATH,
    DESKTOP_DIR,
    GLOBAL_DESKTOP_DIR,
    ICON_PATH,
    LOCAL_DESKTOP_DIR,
    PYTHON_EXECUTABLE,
    SIDEBAR_WIDTH,
    STYLE_PATH,
)
